CREATE TABLE tightening_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deleted INTEGER,
    creator_id INTEGER,
    modifier_id INTEGER,
    create_time TEXT,
    modify_time TEXT,
    mission_record_id INTEGER NOT NULL,
    workstation_name TEXT,
    tool_name TEXT,
    tool_type_name TEXT,
    product_side_name TEXT,
    bolt_serial_num INTEGER,
    arm_location TEXT,
    parameter_set INTEGER,
    parameter_set_name TEXT,
    tightening_id INTEGER,
    tightening_result INTEGER,
    result_type INTEGER,
    torque_result INTEGER,
    angle_result INTEGER,
    rundown_angle_result INTEGER,
    torque_values_unit INTEGER,
    torque_min_limit REAL,
    torque_max_limit REAL,
    torque_final_target REAL,
    torque REAL,
    angle_min_limit REAL,
    angle_max_limit REAL,
    angle_final_target REAL,
    angle REAL,
    rundown_angle_min_limit REAL,
    rundown_angle_max_limit REAL,
    rundown_angle REAL,
    timestamp TEXT
);
